export const SET_CURVE_PARAMETERS = 'SET_CURVE_PARAMETERS';
export const ADD_TRADER = 'ADD_TRADER';
export const BUY_TOKEN = 'BUY_TOKEN';
export const SELL_TOKEN = 'SELL_TOKEN';
export const TOGGLE_SHOW_CHARTS = 'TOGGLE_SHOW_CHARTS';
export const SET_CURVE_DATA = 'SET_CURVE_DATA';
